public with sharing class Constants_CloneApp {
	
	public static final map<String, String> APPLICANTINFO_NOT_CLONED_FIELDS = new Map<String,String>{
		'Years_in_Home__c' => 'Years_in_Home__c',
		'Business_in_Home__c' => 'Business_in_Home__c',
		'Business_in_Home_Description__c' => 'Business_in_Home_Description__c',
		'Previous_Address_Complete__c' => 'Previous_Address_Complete__c',
		'Primary_Language__c' => 'Primary_Language__c',
		'Smoker_in_Family__c' => 'Smoker_in_Family__c',
		'Pets__c' => 'Pets__c',
		'Pets_Description__c' => 'Pets_Description__c',
		'Pet_Types__c' => 'Pet_Types__c',
		'Special_Diet_Indicated__c' => 'Special_Diet_Indicated__c',
		'Special_Diet__c' => 'Special_Diet__c',
		'Special_Diet_Description__c' => 'Special_Diet_Description__c',
		'Special_Diet_Expectations__c' => 'Special_Diet_Expectations__c',
		'Special_Diet_Expectation_Description__c' => 'Special_Diet_Expectation_Description__c',
		'Engagement_Start__c' => 'Engagement_Start__c',
		'Gender_Preference__c' => 'Gender_Preference__c',
		'Family_Members_Complete__c'  => 'Family_Members_Complete__c',
		'Pax__c' => 'Pax__c',
		'Nationality_Preferences__c' => 'Nationality_Preferences__c',
		'Religious_Sharing_Indicated__c' => 'Religious_Sharing_Indicated__c',
		'Religious_Restriction_Indicated__c' => 'Religious_Restriction_Indicated__c',
		'Host_Special_Diet__c' => 'Host_Special_Diet__c',
		'Daily_Meal_Commitment__c' => 'Daily_Meal_Commitment__c',
		'Prior_Host_Experience__c' => 'Prior_Host_Experience__c',
		'Prior_Hosting_Agency__c' => 'Prior_Hosting_Agency__c',
		'Prior_Host_Description__c' => 'Prior_Host_Description__c',
		'Exchange_Agency_Employment__c' => 'Exchange_Agency_Employment__c',
		'How_Heard__c' => 'How_Heard__c',
		'RB_First_Name__c' => 'RB_First_Name__c',
		'RB_Last_Name__c' => 'RB_Last_Name__c', 
		'Opportunity_Name__c' => 'Opportunity_Name__c'		
	};
	
	public static final map<String, String> PERSONINFO_NOT_CLONED_FIELDS = new map<String, String>{
		'Background_Check__c' => 'Background_Check__c', 
		'Background_Check_Msg__c' => 'Background_Check_Msg__c',
		'Background_Check_Consent_Received__c' => 'Background_Check_Consent_Received__c', 
		'BGC_Notes__c' => 'BGC_Notes__c', 
		'Background_Check_Id__c' => 'Background_Check_Id__c', 
		'Background_Check_By__c' => 'Background_Check_By__c', 
		'Background_Check_At__c' => 'Background_Check_At__c'		
	};

}