/**
 * 	Description 	:	Apex class to hold constants like variables.
 * 
 * 	Created By		:	
 * 
 * 	Created Date	:	02/18/2014
 * 
 * 	Revision Logs	:	V1.0 - Created
 *
**/
public class PaymentConstants {
	
	//Variable helpful in AWS Payment Web Service
	public final static String RESPONSE_RECEIVED_FROM_PAYMENT_SERVER = 'Response Received from Payment Server: ';
	public final static String TRANSACTION_ID = 'TransactionID:';
	public final static String SUCCESS_STATUS = 'SuccessStatus:';
	public final static String APPROVAL_CODE = 'ApprovalCode:';
	public final static String TRUE_CLIENT_IP = 'True-Client-IP';
	public final static String X_SALESFORCE_SIP = 'X-Salesforce-SIP';
	
}