@isTest
private class Test_Docusign_API {

    static testMethod void myUnitTest() {
    	new DocuSignAPI.PublishConnectFailures_element();
    	new DocuSignAPI.VoidEnvelope_element();
		new DocuSignAPI.Reminders();
		new DocuSignAPI.ArrayOfInlineTemplate();
		new DocuSignAPI.BrandRequestItem();
		new DocuSignAPI.RecipientEsignList();
		new DocuSignAPI.BrandResults();
		new DocuSignAPI.UpdateAddressBookItems_element();
		new DocuSignAPI.DeleteEnvelopesResponse_element();
		new DocuSignAPI.CreateEnvelopeFromTemplatesAndForms_element();
		new DocuSignAPI.SendEnvelope_element();
		new DocuSignAPI.RequestDocumentPDFsEx_element();
		new DocuSignAPI.AuthoritativeCopyExportStatus();
		new DocuSignAPI.SynchEnvelopeResponse_element();
		new DocuSignAPI.ArrayOfFolderItem();
		new DocuSignAPI.EnvelopeStatus();
		new DocuSignAPI.GetRecipientEsignList_element();
		new DocuSignAPI.EventResult();
		new DocuSignAPI.CreateEnvelopeResponse_element();
		new DocuSignAPI.RecipientCorrectionStatus();
		new DocuSignAPI.SSN4Information();
		new DocuSignAPI.Expirations();
		new DocuSignAPI.RequestPDFNoWaterMark_element();
		new DocuSignAPI.RequestDocumentPDFsRecipientsViewResponse_element();
		new DocuSignAPI.DocuSignEnvelopeInformation();
		new DocuSignAPI.FolderItem();
		new DocuSignAPI.RequestPDFsWithOptions_element();
		new DocuSignAPI.RequestDocumentPDFsRecipientsView_element();
		new DocuSignAPI.GetFolderList_element();
		new DocuSignAPI.RequestStatusesResponse_element();
		new DocuSignAPI.CreateAccountBrands_element();
		new DocuSignAPI.RecipientCorrectionCorrectedCaptiveInfo();
		new DocuSignAPI.CreateAccountBrandsResponse_element();
		new DocuSignAPI.GetStatusInDocuSignConnectFormatResponse_element();
		new DocuSignAPI.ArrayOfConnectFailure();
		new DocuSignAPI.CreateAndSendEnvelope_element();
		new DocuSignAPI.ArrayOfMatchBox();
		new DocuSignAPI.RequestRecipientToken_element();
		new DocuSignAPI.TransferEnvelopeStatus();
		new DocuSignAPI.ArrayOfDocumentStatus();
		new DocuSignAPI.ArrayOfEnvelopeStatusCode();
		new DocuSignAPI.RecipientList();
		new DocuSignAPI.RequestTemplateList_element();
		new DocuSignAPI.RequestStatusCodes_element();
		new DocuSignAPI.IDCheckInformation();
		new DocuSignAPI.ServerTemplate();
		new DocuSignAPI.RemoveAddressBookItems_element();
		new DocuSignAPI.IDCheckInformationInput();
		new DocuSignAPI.PDFOptions();
		new DocuSignAPI.RequestTemplateListResponse_element();
		new DocuSignAPI.GetFolderItems_element();
		new DocuSignAPI.ArrayOfRecipient();
		new DocuSignAPI.FilteredEnvelopeStatusChanges();
		new DocuSignAPI.AddressBookPhoneNumber();
		new DocuSignAPI.MoveEnvelopesArg();
		new DocuSignAPI.ArrayOfFolder();
		new DocuSignAPI.EnvelopeAuditEventsResponse_element();
		new DocuSignAPI.MatchBox();
		new DocuSignAPI.UserInfo();
		new DocuSignAPI.VoidEnvelopeStatus();
		new DocuSignAPI.RecipientSignatureInfo();
		new DocuSignAPI.ArrayOfTemplateReferenceFieldDataDataValue();
		new DocuSignAPI.SSN9Information();
		new DocuSignAPI.AvailableFolders();
		new DocuSignAPI.FormDataXfdfField();
		new DocuSignAPI.TemplateReference();
		new DocuSignAPI.CreateEnvelopeFromTemplates_element();
		new DocuSignAPI.ArrayOfAttachment();
		new DocuSignAPI.GetRecipientListResponse_element();
		new DocuSignAPI.GetRecipientList_element();
		new DocuSignAPI.DeleteEnvelopes_element();
		new DocuSignAPI.ArrayOfDocumentPDF();
		new DocuSignAPI.MoveEnvelopesResponse_element();
		new DocuSignAPI.CreateEnvelopeFromTemplatesAndFormsResponse_element();
		new DocuSignAPI.BrandDefinitions();
		new DocuSignAPI.InlineTemplate();
		new DocuSignAPI.EnvelopeAuditEventsResult_element();
		new DocuSignAPI.UploadTemplateResponse_element();
		new DocuSignAPI.PublishConnectFailuresResult();
		new DocuSignAPI.DeleteAccountBrandsResponse_element();
		new DocuSignAPI.EnvelopeStatusChangeFilter();
		new DocuSignAPI.CustomField();
		new DocuSignAPI.SaveTemplateResponse_element();
		new DocuSignAPI.ArrayOfTemplateReferenceRoleAssignment();
		new DocuSignAPI.ArrayOfBrandRequestItem();
		new DocuSignAPI.ArrayOfTabStatus();
		new DocuSignAPI.TransferEnvelope_element();
		new DocuSignAPI.PurgeDocuments_element();
		new DocuSignAPI.RequestTemplates_element();
		new DocuSignAPI.GetAddressBookItemsResponse_element();
		new DocuSignAPI.AccountSetting();
		new DocuSignAPI.AddressInformationInput();
		new DocuSignAPI.TemplateReferenceRoleAssignment();
		new DocuSignAPI.AccountMembershipFeaturesList();
		new DocuSignAPI.ArrayOfEnvelopeEvent();
		new DocuSignAPI.AccountSettingsList();
		new DocuSignAPI.PublishConnectFailuresFilter();
		new DocuSignAPI.TransferEnvelopeResponse_element();
		new DocuSignAPI.SendEnvelopeResponse_element();
		new DocuSignAPI.SSN4InformationInput();
		new DocuSignAPI.RequestTemplateResponse_element();
		new DocuSignAPI.RequestStatus_element();
		new DocuSignAPI.ArrayOfServerTemplate();
		new DocuSignAPI.UploadTemplate_element();
		new DocuSignAPI.ConnectFailuresFilter();
		new DocuSignAPI.RequestDocumentPDFsResponse_element();
		new DocuSignAPI.EnvelopePDF();
		new DocuSignAPI.RequestPDFNoWaterMarkResponse_element();
		new DocuSignAPI.FormData();
		new DocuSignAPI.RequestPDF_element();
		new DocuSignAPI.ArrayOfAddressBookItem1();
		new DocuSignAPI.TabStatus();
		new DocuSignAPI.FilteredEnvelopeStatuses();
		new DocuSignAPI.FoldersFilter();
		new DocuSignAPI.RequestCertificate_element();
		new DocuSignAPI.EnvelopeEvent();
		new DocuSignAPI.SaveTemplateResult();
		new DocuSignAPI.PDFMetaDataTemplate();
		new DocuSignAPI.RequestPDFResponse_element();
		new DocuSignAPI.FolderFilter();
		new DocuSignAPI.CreateAndSendEnvelopeResponse_element();
		new DocuSignAPI.GetAccountMembershipFeaturesList_element();
		new DocuSignAPI.GetAddressBookItems_element();
		new DocuSignAPI.ArrayOfPositiveInteger();
		new DocuSignAPI.RequestStatusCodesResponse_element();
		new DocuSignAPI.ArrayOfTemplateReference();
		new DocuSignAPI.Attachment();
		new DocuSignAPI.RequestPDFWithCert_element();
		new DocuSignAPI.UpdateAddressBookResult();
		new DocuSignAPI.SSN9InformationInput();
		new DocuSignAPI.RequestEnvelopeResponse_element();
		new DocuSignAPI.TemplateReferenceFieldDataDataValue();
		new DocuSignAPI.MoveEnvelopes_element();
		new DocuSignAPI.AddressBookRemoveItem();
		new DocuSignAPI.RecipientPhoneAuthentication();
		new DocuSignAPI.RequestEnvelope_element();
		new DocuSignAPI.AddressBookItem();
		new DocuSignAPI.SaveTemplate_element();
		new DocuSignAPI.RecipientStatusEsignAgreementInformation();
		new DocuSignAPI.GetConnectFailuresResponse_element();
		new DocuSignAPI.CompositeTemplate();
		new DocuSignAPI.FolderResults();
		new DocuSignAPI.PurgeDocumentsResponse_element();
		new DocuSignAPI.EnvelopeSettings();
		new DocuSignAPI.DOBInformationInput();
		new DocuSignAPI.RequestStatusesEx_element();
		new DocuSignAPI.RequestDocumentPDFs_element();
		new DocuSignAPI.DocumentPDF();
		new DocuSignAPI.RequestDocumentPDFsExResponse_element();
		new DocuSignAPI.ArrayOfEnvelopeTemplate();
		new DocuSignAPI.DocumentPDFs();
		new DocuSignAPI.SynchEnvelope_element();
		new DocuSignAPI.EnvelopeAuditEvents_element();
		new DocuSignAPI.TemplateReferenceFieldData();
		new DocuSignAPI.FormDataXfdf();
		new DocuSignAPI.Notification();
		new DocuSignAPI.AcknowledgeAuthoritativeCopyExport_element();
		new DocuSignAPI.RequestCorrectTokenResponse_element();
		new DocuSignAPI.AcknowledgeAuthoritativeCopyExportResponse_element();
		new DocuSignAPI.VoidEnvelopeResponse_element();
		new DocuSignAPI.RequestRecipientTokenAuthenticationAssertion();
		new DocuSignAPI.RequestPDFsWithOptionsResponse_element();
		new DocuSignAPI.CorrectAndResendEnvelopeResponse_element();
		new DocuSignAPI.PDFsOptions();
		new DocuSignAPI.GetAccountBrandsResponse_element();
		new DocuSignAPI.GetAccountSettingsListResponse_element();
		new DocuSignAPI.RecipientCaptiveInfo();
		new DocuSignAPI.ArrayOfAddressBookRemoveItem();
		new DocuSignAPI.ArrayOfBrandResultItem();
		new DocuSignAPI.RequestPDFWithCertResponse_element();
		new DocuSignAPI.DOBInformation();
		new DocuSignAPI.GetStatusInDocuSignConnectFormat_element();
		new DocuSignAPI.RequestRecipientTokenClientURLs();
		new DocuSignAPI.SynchEnvelopeStatus();
		new DocuSignAPI.RequestStatusEx_element();
		new DocuSignAPI.GetRecipientEsignListResponse_element();
		new DocuSignAPI.RecipientStatus();
		new DocuSignAPI.RequestStatusChanges_element();
		new DocuSignAPI.RequestSenderTokenResponse_element();
		new DocuSignAPI.RequestRecipientFaxTokenResponse_element();
		new DocuSignAPI.RecipientCorrection();
		new DocuSignAPI.RequestPDFWithOptionsResponse_element();
		new DocuSignAPI.ArrayOfEnvelopeStatusChange();
		new DocuSignAPI.RequestStatusesExResponse_element();
		new DocuSignAPI.RecipientEsign();
		new DocuSignAPI.Envelope();
		new DocuSignAPI.EnvelopeTemplates();
		new DocuSignAPI.PingResponse_element();
		new DocuSignAPI.EnvelopeStatusFilterBeginDateTime();
		new DocuSignAPI.RequestStatuses_element();
		new DocuSignAPI.ArrayOfTab();
		new DocuSignAPI.VaultingOptions();
		new DocuSignAPI.RemoveAddressBookItemsResponse_element();
		new DocuSignAPI.CreateEnvelope_element();
		new DocuSignAPI.AddressInformation();
		new DocuSignAPI.AnchorTab();
		new DocuSignAPI.VaultingDetails();
		new DocuSignAPI.GetAuthenticationTokenResponse_element();
		new DocuSignAPI.RequestRecipientTokenResponse_element();
		new DocuSignAPI.RequestPDFWithOptions_element();
		new DocuSignAPI.ArrayOfAddressBookItem();
		new DocuSignAPI.EnvelopeInformation();
		new DocuSignAPI.ArrayOfCustomField();
		new DocuSignAPI.ArrayOfEnvelopeStatus();
		new DocuSignAPI.ConnectFailure();
		new DocuSignAPI.RecipientEmailNotification();
		new DocuSignAPI.RequestCertificateResponse_element();
		new DocuSignAPI.DeleteEnvelopesArg();
		new DocuSignAPI.ErrorDetails();
		new DocuSignAPI.BrandResultItem();
		new DocuSignAPI.EnvelopeTemplate();
		new DocuSignAPI.DocumentStatus();
		new DocuSignAPI.Tab();
		new DocuSignAPI.PublishConnectFailuresResponse_element();
		new DocuSignAPI.ArrayOfRecipient1();
		new DocuSignAPI.Recipient();
		new DocuSignAPI.ArrayOfFormDataXfdfField();
		new DocuSignAPI.RequestTemplatesResponse_element();
		new DocuSignAPI.ArrayOfRecipientEsign();
		new DocuSignAPI.UpdateAddressBookItemsResponse_element();
		new DocuSignAPI.ExportAuthoritativeCopy_element();
		new DocuSignAPI.RequestRecipientFaxToken_element();
		new DocuSignAPI.ArrayOfString();
		new DocuSignAPI.RequestTemplate_element();
		new DocuSignAPI.EnvelopeStatusFilter();
		new DocuSignAPI.CorrectionStatus();
		new DocuSignAPI.ArrayOfDocument();
		new DocuSignAPI.PurgeDocumentStatus();
		new DocuSignAPI.EnvelopeTemplateDefinition();
		new DocuSignAPI.RequestSenderToken_element();
		new DocuSignAPI.RequestStatusExResponse_element();
		new DocuSignAPI.CreateEnvelopeFromTemplatesResponse_element();
		new DocuSignAPI.BrandDeleteRequest();
		new DocuSignAPI.ArrayOfString3();
		new DocuSignAPI.ArrayOfString4();
		new DocuSignAPI.ArrayOfString1();
		new DocuSignAPI.ArrayOfString2();
		new DocuSignAPI.RequestCorrectToken_element();
		new DocuSignAPI.ArrayOfString5();
		new DocuSignAPI.AuthenticationStatus();
		new DocuSignAPI.DeleteAccountBrands_element();
		new DocuSignAPI.Ping_element();
		new DocuSignAPI.GetConnectFailures_element();
		new DocuSignAPI.ArrayOfCompositeTemplate();
		new DocuSignAPI.GetAccountBrands_element();
		new DocuSignAPI.Correction();
		new DocuSignAPI.RequestStatusChangesResponse_element();
		new DocuSignAPI.Document();
		new DocuSignAPI.EventNotification();
		new DocuSignAPI.Folder();
		new DocuSignAPI.RequestStatusResponse_element();
		new DocuSignAPI.EnvelopeStatusChange();
		new DocuSignAPI.FolderTypeInfo();
		new DocuSignAPI.ArrayOfPublishConnectFailuresResult();
		new DocuSignAPI.GetAccountMembershipFeaturesListResponse_element();
		new DocuSignAPI.CorrectAndResendEnvelope_element();
		new DocuSignAPI.GetAuthenticationToken_element();
		new DocuSignAPI.ArrayOfRecipientStatus();
		new DocuSignAPI.GetFolderItemsResponse_element();
		new DocuSignAPI.ArrayOfRecipientCorrection();
		new DocuSignAPI.APIServiceSoap();
		new DocuSignAPI.AuthoritativeCopyExportDocuments();
		new DocuSignAPI.GetFolderListResponse_element();
		new DocuSignAPI.ExportAuthoritativeCopyResponse_element();
		new DocuSignAPI.GetAccountSettingsList_element();
		new DocuSignAPI.ArrayOfRecipientCorrectionStatus();
		
		DocuSignAPI.APIServiceSoap soapcall = new DocuSignAPI.APIServiceSoap();
		try
		{
			DocuSignAPI.AccountSettingsList acclist = soapcall.GetAccountSettingsList('TestAccount');
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		
		try
		{
			DocuSignAPI.EnvelopeStatus envst = soapcall.RequestStatusEx('TestAccount33');
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		
		try
		{
			DocuSignAPI.ArrayOfAddressBookItem addbook = soapcall.GetAddressBookItems('TestAccount32');
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		
		try
		{
			DocuSignAPI.DocuSignEnvelopeInformation envinfo = soapcall.GetStatusInDocuSignConnectFormat('TestAccount21');
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		
		try
		{
			DocuSignAPI.PurgeDocumentStatus PurgeSt = soapcall.PurgeDocuments('TestAccount11');
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		
		try
		{
			DocuSignAPI.EnvelopePDF envPDF = soapcall.RequestPDF('TestAccount11');
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		
		try
		{
			DocuSignAPI.EnvelopePDF envPDFf = soapcall.RequestPDFWithCert('TestAccount11',true);
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		
		try
		{
			DocuSignAPI.VoidEnvelopeStatus voidEnv = soapcall.VoidEnvelope('TestAccount11','testing');
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		
		try
		{
			DocuSignAPI.TransferEnvelopeStatus Trans = soapcall.TransferEnvelope('TestAccount11','testing','Test');
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		try
		{
			DocuSignAPI.AuthoritativeCopyExportDocuments Authr = soapcall.ExportAuthoritativeCopy('TestAccount11');
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		
		try
		{
			DocuSignAPI.RecipientEsignList RecList = soapcall.GetRecipientEsignList('TestAccount11','testtt','testtt','ttttt');
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		
		try
		{
			DocuSignAPI.EnvelopeTemplates EnvT = soapcall.RequestTemplates('TestAccount11',false);
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		
		try
		{
			DocuSignAPI.SynchEnvelopeStatus SyncEnv = soapcall.SynchEnvelope('TestAccount11','Test666',false);
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		
		try
		{
			DocuSignAPI.EnvelopeStatus envRSt = soapcall.RequestStatus('TestAccount11');
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		
		try
		{
			string Rtoken = soapcall.RequestSenderToken('TestAccount11','test','http://www.test.com');
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		
		try
		{
			DocuSignAPI.AuthoritativeCopyExportStatus AuthRtoken = soapcall.AcknowledgeAuthoritativeCopyExport('TestAccount11','test','test');
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		
		try
		{
			boolean png = soapcall.ping();
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		
		try
		{
			DocuSignAPI.DocumentPDFs DocPDF = soapcall.RequestDocumentPDFs('TestEnv');
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		
		try
		{
			DocuSignAPI.RecipientList RList = soapcall.GetRecipientList('TestEnv','test@test.com');
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		
		try
		{
			string GetAuthToken = soapcall.GetAuthenticationToken('TestEnv');
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		
		try
		{
			DocuSignAPI.EnvelopePDF Envpf = soapcall.RequestPDFNoWaterMark('TestEnv');
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		
		try
		{
			DocuSignAPI.EnvelopeAuditEventsResult_element EnvResElem = soapcall.EnvelopeAuditEvents('TestEnv');
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		
		try
		{
			DocuSignAPI.DocumentPDFs DocPFDs = soapcall.RequestDocumentPDFsEx('TestEnv');
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		
		try
		{
			DocuSignAPI.SaveTemplateResult SaveTemp = soapcall.UploadTemplate('TestEnv','test',false);
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		
		try
		{
			DocuSignAPI.BrandResults BList = soapcall.GetAccountBrands('TestEnv');
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		
		try
		{
			DocuSignAPI.DocumentPDFs DF = soapcall.RequestCertificate('TestEnv');
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		
		try
		{
			string ReqCorrect = soapcall.RequestCorrectToken('TestEnv',false,'test');
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		
		try
		{
			DocuSignAPI.Envelope EnvNum = soapcall.RequestEnvelope('TestEnv',false);
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		
		try
		{
			DocuSignAPI.AccountMembershipFeaturesList AcctMem = soapcall.GetAccountMembershipFeaturesList('TestEnv');
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		
		try
		{
			DocuSignAPI.EnvelopeStatus EnvpSt = soapcall.SendEnvelope('TestEnv','test');
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		
		try
		{
			DocuSignAPI.EnvelopeTemplate EnvopTemp = soapcall.RequestTemplate('TestEnv',false);
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		
		try
		{
			DocuSignAPI.DocumentPDFs ReqDocPDFs = soapcall.RequestDocumentPDFsRecipientsView('TestEnv','test','test');
		}
		catch(Exception e)
		{
        	System.debug('Exception Caught'+e);
		}
		
    }
}